import type { McpToolDefinition } from './types.js';

/**
 * Map of tool definitions by name
 */
export const toolDefinitionMap: Map<string, McpToolDefinition> = new Map([

  ["get_status", {
    name: "get_status",
    description: `Returns service status / health`,
    inputSchema: {"type":"object","properties":{}},
    method: "get",
    pathTemplate: "/status",
    executionParameters: [],
    requestBodyContentType: undefined,
  }],
  ["add_watermark", {
    name: "add_watermark",
    description: `Adds a text or an image watermark to PDF document from base64 string or a remote URL.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"oneOf":[{"type":"object","required":["file_url","watermark"],"properties":{"file_url":{"description":"PDF file from remote URL to add the watermark to","type":"string"},"watermark":{"description":"Watermark configuration with image and/or text options","type":"object","properties":{"image":{"anyOf":[{"type":"object","required":["content_url"],"properties":{"content_url":{"description":"URL to an image","type":"string"},"position":{"description":"Watermark position","type":"string","enum":["top-left","top-center","top-right","left","center","right","bottom-left","bottom-center","bottom-right"],"default":"center"},"rotation":{"description":"Watermark rotation","type":"integer","minimum":-180,"maximum":180,"default":0},"scale":{"description":"Watermark image scale","type":"number","minimum":0.05,"maximum":1,"default":1}}},{"type":"object","required":["content_base64"],"properties":{"content_base64":{"description":"Base64 image string","type":"string"},"position":{"description":"Watermark position","type":"string","enum":["top-left","top-center","top-right","left","center","right","bottom-left","bottom-center","bottom-right"],"default":"center"},"rotation":{"description":"Watermark rotation","type":"integer","minimum":-180,"maximum":180,"default":0},"scale":{"description":"Watermark image scale","type":"number","minimum":0.05,"maximum":1,"default":1}}}]},"text":{"type":"object","required":["content"],"properties":{"content":{"description":"Watermark text","type":"string"},"color":{"description":"Watermark text color in hexadecimal format","type":"string","default":"#000000"},"size":{"description":"Watermark text font size in px","type":"integer","minimum":7,"maximum":80,"default":48},"opacity":{"description":"Watermark text opaxity","type":"number","minimum":0.1,"maximum":1,"default":0.5},"position":{"description":"Watermark position","type":"string","enum":["top-left","top-center","top-right","left","center","right","bottom-left","bottom-center","bottom-right"],"default":"center"},"rotation":{"description":"Watermark rotation","type":"integer","minimum":-180,"maximum":180,"default":0}}}}},"output":{"description":"Returned document output","type":"string","enum":["file","base64","url"],"default":"base64"},"name":{"description":"File name of the returned document","type":"string"}}},{"type":"object","required":["file_base64","watermark"],"properties":{"file_base64":{"description":"PDF file from base64 string to add the watermark to","type":"string"},"watermark":{"description":"Watermark configuration with image and/or text options","type":"object","properties":{"image":{"anyOf":[{"type":"object","required":["content_url"],"properties":{"content_url":{"description":"URL to an image","type":"string"},"position":{"description":"Watermark position","type":"string","enum":["top-left","top-center","top-right","left","center","right","bottom-left","bottom-center","bottom-right"],"default":"center"},"rotation":{"description":"Watermark rotation","type":"integer","minimum":-180,"maximum":180,"default":0},"scale":{"description":"Watermark image scale","type":"number","minimum":0.05,"maximum":1,"default":1}}},{"type":"object","required":["content_base64"],"properties":{"content_base64":{"description":"Base64 image string","type":"string"},"position":{"description":"Watermark position","type":"string","enum":["top-left","top-center","top-right","left","center","right","bottom-left","bottom-center","bottom-right"],"default":"center"},"rotation":{"description":"Watermark rotation","type":"integer","minimum":-180,"maximum":180,"default":0},"scale":{"description":"Watermark image scale","type":"number","minimum":0.05,"maximum":1,"default":1}}}]},"text":{"type":"object","required":["content"],"properties":{"content":{"description":"Watermark text","type":"string"},"color":{"description":"Watermark text color in hexadecimal format","type":"string","default":"#000000"},"size":{"description":"Watermark text font size in px","type":"integer","minimum":7,"maximum":80,"default":48},"opacity":{"description":"Watermark text opaxity","type":"number","minimum":0.1,"maximum":1,"default":0.5},"position":{"description":"Watermark position","type":"string","enum":["top-left","top-center","top-right","left","center","right","bottom-left","bottom-center","bottom-right"],"default":"center"},"rotation":{"description":"Watermark rotation","type":"integer","minimum":-180,"maximum":180,"default":0}}}}},"output":{"description":"Returned document output","type":"string","enum":["file","base64","url"],"default":"base64"},"name":{"description":"File name of the returned document","type":"string"}}}],"description":"The JSON request body."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/pdfservices/watermark",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["encrypt_document", {
    name: "encrypt_document",
    description: `Encrypts a PDF document from base64 string or a remote URL.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"oneOf":[{"type":"object","required":["file_url","owner_password"],"properties":{"file_url":{"description":"Public URL to a PDF document","type":"string","format":"https://examplepdf.com"},"owner_password":{"description":"An owner password to open the encrypted document","type":"string"},"user_password":{"description":"An user password to open the encrypted document","type":"string"},"name":{"description":"Name for the PDF file","type":"string"},"output":{"description":"Returned document output format","type":"string","enum":["file","base64","url"],"default":"base64"}}},{"type":"object","required":["file_base64","owner_password"],"properties":{"file_base64":{"description":"PDF document in base64 encoded string format","type":"string"},"owner_password":{"description":"An owner password to open the encrypted document","type":"string"},"user_password":{"description":"An user password to open the encrypted document","type":"string"},"name":{"description":"Name for the PDF file","type":"string"},"output":{"description":"Returned document output format","type":"string","enum":["file","base64","url"],"default":"base64"}}}],"description":"The JSON request body."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/pdfservices/encrypt",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["decrypt_document", {
    name: "decrypt_document",
    description: `Decrypts an encrypted PDF document from base64 string or a remote URL.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"oneOf":[{"type":"object","required":["file_url","owner_password"],"properties":{"file_url":{"description":"Public URL to a PDF document","type":"string","format":"https://examplepdf.com"},"owner_password":{"description":"An owner password to open the encrypted document","type":"string"},"user_password":{"description":"An user password to open the encrypted document","type":"string"},"name":{"description":"Name for the PDF file","type":"string"},"output":{"description":"Returned document output format","type":"string","enum":["file","base64","url"],"default":"base64"}}},{"type":"object","required":["file_base64","owner_password"],"properties":{"file_base64":{"description":"PDF document in base64 encoded string format","type":"string"},"owner_password":{"description":"An owner password to open the encrypted document","type":"string"},"user_password":{"description":"An user password to open the encrypted document","type":"string"},"name":{"description":"Name for the PDF file","type":"string"},"output":{"description":"Returned document output format","type":"string","enum":["file","base64","url"],"default":"base64"}}}],"description":"The JSON request body."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/pdfservices/decrypt",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["optimize_document", {
    name: "optimize_document",
    description: `Optimizes the size of a PDF document from base64 string or a remote URL.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"oneOf":[{"type":"object","required":["file_url"],"properties":{"file_url":{"description":"Public URL to a PDF document","type":"string","format":"https://examplepdf.com"},"name":{"description":"Name for the PDF file","type":"string"},"output":{"description":"Returned document output format","type":"string","enum":["file","base64","url"],"default":"base64"}}},{"type":"object","required":["file_base64"],"properties":{"file_base64":{"description":"PDF document in base64 encoded string format","type":"string"},"name":{"description":"Name for the PDF file","type":"string"},"output":{"description":"Returned document output format","type":"string","enum":["file","base64","url"],"default":"base64"}}}],"description":"The JSON request body."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/pdfservices/optimize",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["make_accessible", {
    name: "make_accessible",
    description: `Adds accessibility tags to a PDF document from base64 string or a remote URL.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"oneOf":[{"type":"object","required":["file_url"],"properties":{"file_url":{"description":"Public URL to a PDF document","type":"string"},"options":{"description":"Processing options (e.g. clear_structure)","type":"array","items":{"type":"string"}},"name":{"description":"Name for the PDF file","type":"string"},"output":{"description":"Returned document output format","type":"string","enum":["file","base64"],"default":"base64"},"metadata":{"description":"Document metadata such as author and language","type":"object","properties":{"author":{"description":"Document author","type":"string"},"language":{"description":"Document language code","type":"string","default":"en"}}}}},{"type":"object","required":["file"],"properties":{"file":{"description":"PDF document in base64 encoded string format","type":"string"},"options":{"description":"Processing options (e.g. clear_structure)","type":"array","items":{"type":"string"}},"name":{"description":"Name for the PDF file","type":"string"},"output":{"description":"Returned document output format","type":"string","enum":["file","base64"],"default":"base64"},"metadata":{"description":"Document metadata such as author and language","type":"object","properties":{"author":{"description":"Document author","type":"string"},"language":{"description":"Document language code","type":"string","default":"en"}}}}}],"description":"The JSON request body."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/pdfservices/make-accessible",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["extract_form_fields", {
    name: "extract_form_fields",
    description: `Extracts form fields and their metadata from a PDF document using base64 string or a remote URL.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"oneOf":[{"type":"object","required":["file_url"],"properties":{"file_url":{"description":"Public URL to a PDF document","type":"string","format":"https://examplepdf.com"},"key_field":{"description":"Specifies which field is used to map the extract fields. If your document contains fields with the same name, then we suggest using the id field. Defaults to name.","type":"string","enum":["name","id"],"default":"name","example":"name"}}},{"type":"object","required":["file_base64"],"properties":{"file_base64":{"description":"PDF document in base64 encoded string format","type":"string"},"key_field":{"description":"Specifies which field is used to map the extract fields. If your document contains fields with the same name, then we suggest using the id field. Defaults to name.","type":"string","enum":["name","id"],"default":"name","example":"name"}}}],"description":"The JSON request body."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/pdfservices/form/fields",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["fill_form_fields", {
    name: "fill_form_fields",
    description: `Fills form fields in a PDF document with provided data from base64 string or a remote URL.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"oneOf":[{"type":"object","required":["file_url","data"],"properties":{"file_url":{"description":"Public URL to a PDF document","type":"string","format":"https://examplepdf.com"},"data":{"description":"Form field data to fill in the PDF","type":"object","example":{"firstName":"John","lastName":"Doe","email":"john.doe@example.com"}},"output":{"description":"Returned document output format","type":"string","enum":["file","base64","url"],"default":"base64"},"name":{"description":"Name for the PDF file","type":"string"}}},{"type":"object","required":["file_base64","data"],"properties":{"file_base64":{"description":"PDF document in base64 encoded string format","type":"string"},"data":{"description":"Form field data to fill in the PDF","type":"object","example":{"firstName":"John","lastName":"Doe","email":"john.doe@example.com"}},"output":{"description":"Returned document output format","type":"string","enum":["file","base64","url"],"default":"base64"},"name":{"description":"Name for the PDF file","type":"string"}}}],"description":"The JSON request body."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/pdfservices/form/fill",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["get_templates", {
    name: "get_templates",
    description: `Returns a list of templates available for the authenticated workspace`,
    inputSchema: {"type":"object","properties":{"name":{"type":"string","description":"Filter template by name"},"tags":{"type":"string","description":"Filter template by tags"},"access":{"type":"string","enum":["private","organization",""],"default":"","description":"Filter template by access type. No values returns all templates. private - returns only private templates, organization - returns only organization templates."},"page":{"type":"number","default":1,"description":"Pagination: page to return"},"per_page":{"type":"number","default":15,"description":"Pagination: How many records to return per page"}}},
    method: "get",
    pathTemplate: "/templates",
    executionParameters: [{"name":"name","in":"query"},{"name":"tags","in":"query"},{"name":"access","in":"query"},{"name":"page","in":"query"},{"name":"per_page","in":"query"}],
    requestBodyContentType: undefined,
  }],
  ["create_template", {
    name: "create_template",
    description: `Creates a new template. If template configuration is not specified in the request body then an empty template is created. Template is placed to the workspace specified in authentication params. Template configuration must be sent in the request body.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"description":"Template configuration","type":"object","required":["name"],"properties":{"name":{"type":"string","description":"Template name"},"tags":{"type":"array","items":{"type":"string"},"description":"A list of tags assigned to a template"},"isDraft":{"type":"boolean","description":"Indicates if the template is a draft or published."},"layout":{"type":"object","description":"Defines template layout (e.g page format, margins).","properties":{"format":{"type":"string","enum":["A4","letter","custom"],"description":"Defines template page size","default":"A4"},"width":{"type":"number","description":"Page width in units"},"height":{"type":"number","description":"Page height in units"},"unit":{"type":"string","description":"Measure unit","enum":["cm","in"],"default":"cm"},"orientation":{"type":"string","description":"Page orientation","enum":["portrait","landscape"]},"rotation":{"type":"number","description":"Page rotation in degrees","enum":[0,90,180,270]},"margins":{"description":"Page margins in units","type":"object","properties":{"top":{"type":"number","description":"Top margin in units"},"right":{"type":"number","description":"Right margin in units"},"bottom":{"type":"number","description":"Bottom margin in units"},"left":{"type":"number","description":"Left margin in units"}}},"repeatLayout":{"description":"Defines page size if layout is repeated on the page e.g sheet labels","type":["object","null"],"properties":{"format":{"type":"string","enum":["A4","letter","custom"],"description":"Defines template page size","example":"A4"},"width":{"type":"number","description":"Page width in units","example":21},"height":{"type":"number","description":"Page height in units","example":29.7}}},"emptyLabels":{"description":"Specifies how many blank lables to add to sheet label.","type":"number","default":0}}},"pages":{"type":"array","description":"Defines page or label size, margins and components on page or label","items":{"type":"object","properties":{"width":{"type":"number","description":"Page width in units"},"height":{"type":"number","description":"Page height in units"},"margins":{"type":"object","properties":{"right":{"type":"number","description":"Page or label margin from right"},"bottom":{"type":"number","description":"Page or label margin from bottom"}}},"border":{"type":"boolean","default":false},"components":{"type":"array","items":{"type":"object"}},"layout":{"type":["object","null"],"description":"Defines page specific layout which can differ from the main template layout (e.g page format, margins)."},"conditionalFormats":{"type":"array","items":{"type":"object"}},"backgroundImage":{"type":["string","null"],"description":"Defines background image for the page."}}}},"dataSettings":{"type":"object","description":"Defines filter and sort option for root data set.","properties":{"sortBy":{"type":"array","items":{"type":"object"}},"filterBy":{"type":"array","items":{"type":"object"}},"transform":{"type":"array","items":{"type":"object"}}}},"editor":{"type":"object","description":"Configuration preferences for the editor","properties":{"heightMultiplier":{"type":"number"}}},"fontSubsetting":{"type":"boolean","description":"If font-subsetting is applied to document when generated","default":false},"barcodeAsImage":{"type":"boolean","description":"Defines if barcodes are rendered as raster images instead of vector graphics.","default":false}}}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/templates",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["get_template_schema", {
    name: "get_template_schema",
    description: `Returns Template JSON Schema which defines the structure of the Template Definition.`,
    inputSchema: {"type":"object","properties":{}},
    method: "get",
    pathTemplate: "/templates/schema",
    executionParameters: [],
    requestBodyContentType: undefined,
  }],
  ["import_template", {
    name: "import_template",
    description: `Creates a template from existing PDF`,
    inputSchema: {"type":"object","properties":{"requestBody":{"oneOf":[{"type":"object","required":["file_url","template"],"properties":{"template":{"description":"Template configuration with name","type":"object","required":["name"],"properties":{"name":{"type":"string","description":"Template name","example":"Invoice template"}}},"file_url":{"description":"PDF file from remote URL to import","type":"string"}}},{"type":"object","required":["file_base64","template"],"properties":{"template":{"description":"Template configuration with name","type":"object","required":["name"],"properties":{"name":{"type":"string","description":"Template name","example":"Invoice template"}}},"file_base64":{"description":"PDF file from base64 string to import","type":"string"}}}],"description":"Import a PDF via URL or base64 string as template"}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/templates/import",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["validate_template", {
    name: "validate_template",
    description: `Validates if the provided template configuration matches the template JSON schema.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"description":"Template configuration","type":"object","required":["name"],"properties":{"name":{"type":"string","description":"Template name"},"tags":{"type":"array","items":{"type":"string"},"description":"A list of tags assigned to a template"},"isDraft":{"type":"boolean","description":"Indicates if the template is a draft or published."},"layout":{"type":"object","description":"Defines template layout (e.g page format, margins).","properties":{"format":{"type":"string","enum":["A4","letter","custom"],"description":"Defines template page size","default":"A4"},"width":{"type":"number","description":"Page width in units"},"height":{"type":"number","description":"Page height in units"},"unit":{"type":"string","description":"Measure unit","enum":["cm","in"],"default":"cm"},"orientation":{"type":"string","description":"Page orientation","enum":["portrait","landscape"]},"rotation":{"type":"number","description":"Page rotation in degrees","enum":[0,90,180,270]},"margins":{"description":"Page margins in units","type":"object","properties":{"top":{"type":"number","description":"Top margin in units"},"right":{"type":"number","description":"Right margin in units"},"bottom":{"type":"number","description":"Bottom margin in units"},"left":{"type":"number","description":"Left margin in units"}}},"repeatLayout":{"description":"Defines page size if layout is repeated on the page e.g sheet labels","type":["object","null"],"properties":{"format":{"type":"string","enum":["A4","letter","custom"],"description":"Defines template page size","example":"A4"},"width":{"type":"number","description":"Page width in units","example":21},"height":{"type":"number","description":"Page height in units","example":29.7}}},"emptyLabels":{"description":"Specifies how many blank lables to add to sheet label.","type":"number","default":0}}},"pages":{"type":"array","description":"Defines page or label size, margins and components on page or label","items":{"type":"object","properties":{"width":{"type":"number","description":"Page width in units"},"height":{"type":"number","description":"Page height in units"},"margins":{"type":"object","properties":{"right":{"type":"number","description":"Page or label margin from right"},"bottom":{"type":"number","description":"Page or label margin from bottom"}}},"border":{"type":"boolean","default":false},"components":{"type":"array","items":{"type":"object"}},"layout":{"type":["object","null"],"description":"Defines page specific layout which can differ from the main template layout (e.g page format, margins)."},"conditionalFormats":{"type":"array","items":{"type":"object"}},"backgroundImage":{"type":["string","null"],"description":"Defines background image for the page."}}}},"dataSettings":{"type":"object","description":"Defines filter and sort option for root data set.","properties":{"sortBy":{"type":"array","items":{"type":"object"}},"filterBy":{"type":"array","items":{"type":"object"}},"transform":{"type":"array","items":{"type":"object"}}}},"editor":{"type":"object","description":"Configuration preferences for the editor","properties":{"heightMultiplier":{"type":"number"}}},"fontSubsetting":{"type":"boolean","description":"If font-subsetting is applied to document when generated","default":false},"barcodeAsImage":{"type":"boolean","description":"Defines if barcodes are rendered as raster images instead of vector graphics.","default":false}}}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/templates/validate",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["get_template", {
    name: "get_template",
    description: `Returns template configuration`,
    inputSchema: {"type":"object","properties":{"templateId":{"type":"number","description":"Template unique identifier"}},"required":["templateId"]},
    method: "get",
    pathTemplate: "/templates/{templateId}",
    executionParameters: [{"name":"templateId","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["update_template", {
    name: "update_template",
    description: `Updates template configuration. The template configuration for pages and layout must be complete as the entire configuration is replaced and not merged.`,
    inputSchema: {"type":"object","properties":{"templateId":{"type":"number","description":"Template unique identifier"},"requestBody":{"description":"Template configuration","type":"object","required":["name"],"properties":{"name":{"type":"string","description":"Template name"},"tags":{"type":"array","items":{"type":"string"},"description":"A list of tags assigned to a template"},"isDraft":{"type":"boolean","description":"Indicates if the template is a draft or published."},"layout":{"type":"object","description":"Defines template layout (e.g page format, margins).","properties":{"format":{"type":"string","enum":["A4","letter","custom"],"description":"Defines template page size","default":"A4"},"width":{"type":"number","description":"Page width in units"},"height":{"type":"number","description":"Page height in units"},"unit":{"type":"string","description":"Measure unit","enum":["cm","in"],"default":"cm"},"orientation":{"type":"string","description":"Page orientation","enum":["portrait","landscape"]},"rotation":{"type":"number","description":"Page rotation in degrees","enum":[0,90,180,270]},"margins":{"description":"Page margins in units","type":"object","properties":{"top":{"type":"number","description":"Top margin in units"},"right":{"type":"number","description":"Right margin in units"},"bottom":{"type":"number","description":"Bottom margin in units"},"left":{"type":"number","description":"Left margin in units"}}},"repeatLayout":{"description":"Defines page size if layout is repeated on the page e.g sheet labels","type":["object","null"],"properties":{"format":{"type":"string","enum":["A4","letter","custom"],"description":"Defines template page size","example":"A4"},"width":{"type":"number","description":"Page width in units","example":21},"height":{"type":"number","description":"Page height in units","example":29.7}}},"emptyLabels":{"description":"Specifies how many blank lables to add to sheet label.","type":"number","default":0}}},"pages":{"type":"array","description":"Defines page or label size, margins and components on page or label","items":{"type":"object","properties":{"width":{"type":"number","description":"Page width in units"},"height":{"type":"number","description":"Page height in units"},"margins":{"type":"object","properties":{"right":{"type":"number","description":"Page or label margin from right"},"bottom":{"type":"number","description":"Page or label margin from bottom"}}},"border":{"type":"boolean","default":false},"components":{"type":"array","items":{"type":"object"}},"layout":{"type":["object","null"],"description":"Defines page specific layout which can differ from the main template layout (e.g page format, margins)."},"conditionalFormats":{"type":"array","items":{"type":"object"}},"backgroundImage":{"type":["string","null"],"description":"Defines background image for the page."}}}},"dataSettings":{"type":"object","description":"Defines filter and sort option for root data set.","properties":{"sortBy":{"type":"array","items":{"type":"object"}},"filterBy":{"type":"array","items":{"type":"object"}},"transform":{"type":"array","items":{"type":"object"}}}},"editor":{"type":"object","description":"Configuration preferences for the editor","properties":{"heightMultiplier":{"type":"number"}}},"fontSubsetting":{"type":"boolean","description":"If font-subsetting is applied to document when generated","default":false},"barcodeAsImage":{"type":"boolean","description":"Defines if barcodes are rendered as raster images instead of vector graphics.","default":false}}}},"required":["templateId","requestBody"]},
    method: "put",
    pathTemplate: "/templates/{templateId}",
    executionParameters: [{"name":"templateId","in":"path"}],
    requestBodyContentType: "application/json",
  }],
  ["delete_template", {
    name: "delete_template",
    description: `Deletes the template from workspace`,
    inputSchema: {"type":"object","properties":{"templateId":{"type":"number","description":"Template unique identifier"}},"required":["templateId"]},
    method: "delete",
    pathTemplate: "/templates/{templateId}",
    executionParameters: [{"name":"templateId","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["get_template_data", {
    name: "get_template_data",
    description: `Returns all data fields used in the template. Returns structured JSON data that can be used to check which data fields are used in template or autogenerate sample data.
`,
    inputSchema: {"type":"object","properties":{"templateId":{"type":"number","description":"Template unique identifier"}},"required":["templateId"]},
    method: "get",
    pathTemplate: "/templates/{templateId}/data",
    executionParameters: [{"name":"templateId","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["copy_template", {
    name: "copy_template",
    description: `Creates a copy of a template to the workspace specified in authentication parameters.`,
    inputSchema: {"type":"object","properties":{"templateId":{"type":"number","description":"Template unique identifier"},"requestBody":{"type":"object","properties":{"name":{"description":"Name for the copied template. If name is not specified then the original name is used.","type":"string"}},"description":"The JSON request body."}},"required":["templateId"]},
    method: "post",
    pathTemplate: "/templates/{templateId}/copy",
    executionParameters: [{"name":"templateId","in":"path"}],
    requestBodyContentType: "application/json",
  }],
  ["open_editor", {
    name: "open_editor",
    description: `Returns an unique URL which you can use to redirect your user to the editor from your application or use the generated URL as iframe source to show the editor within your application.
When using iframe, make sure that your browser allows third-party cookies.
`,
    inputSchema: {"type":"object","properties":{"templateId":{"type":"number","description":"Template unique identifier"},"requestBody":{"type":"object","properties":{"data":{"description":"Data used to generate the document. This can be an object or array of objects.","oneOf":[{"type":"object","description":"JSON data used to replace data fields in the template","example":{"id":123,"name":"John Smith","birthdate":"2000-01-01","role":"Developer"}},{"type":"array","description":"JSON data used to replace data fields in the template","items":{"type":"object","description":"JSON data used to replace data fields in the template","example":{"id":123,"name":"John Smith","birthdate":"2000-01-01","role":"Developer"}},"example":[{"id":123,"name":"John Smith","birthdate":"2000-05-12","role":"Developer"},{"id":123,"name":"Jane Doe","birthdate":"1999-03-12","role":"Manager"}]}]},"language":{"type":"string","enum":["en","et","cs","sk","ru","de"],"description":"Specify the editor UI language. Defaults to organization editor language."}},"description":"The JSON request body."}},"required":["templateId","requestBody"]},
    method: "post",
    pathTemplate: "/templates/{templateId}/editor",
    executionParameters: [{"name":"templateId","in":"path"}],
    requestBodyContentType: "application/json",
  }],
  ["list_template_versions", {
    name: "list_template_versions",
    description: `Returns a paginated list of template versions for the specified template.
`,
    inputSchema: {"type":"object","properties":{"templateId":{"type":"number","description":"Template unique identifier"},"per_page":{"type":"number","description":"Number of items per page."},"page":{"type":"number","description":"Page number to return."}},"required":["templateId"]},
    method: "get",
    pathTemplate: "/templates/{templateId}/versions",
    executionParameters: [{"name":"templateId","in":"path"},{"name":"per_page","in":"query"},{"name":"page","in":"query"}],
    requestBodyContentType: undefined,
  }],
  ["get_template_version", {
    name: "get_template_version",
    description: `Returns the template definition of the specified version.
`,
    inputSchema: {"type":"object","properties":{"templateId":{"type":"number","description":"Template unique identifier"},"templateVersion":{"type":"number","description":"Unique ID of the template version."}},"required":["templateId","templateVersion"]},
    method: "get",
    pathTemplate: "/templates/{templateId}/versions/{templateVersion}",
    executionParameters: [{"name":"templateId","in":"path"},{"name":"templateVersion","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["delete_template_version", {
    name: "delete_template_version",
    description: `Deletes the specified template version.
Production versions cannot be deleted.
`,
    inputSchema: {"type":"object","properties":{"templateId":{"type":"number","description":"Template unique identifier"},"templateVersion":{"type":"number","description":"Unique ID of the template version."}},"required":["templateId","templateVersion"]},
    method: "delete",
    pathTemplate: "/templates/{templateId}/versions/{templateVersion}",
    executionParameters: [{"name":"templateId","in":"path"},{"name":"templateVersion","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["promote_template_version", {
    name: "promote_template_version",
    description: `Promotes the specified template version to production.
Only one version can be production at a time.
`,
    inputSchema: {"type":"object","properties":{"templateId":{"type":"number","description":"Template unique identifier"},"templateVersion":{"type":"number","description":"Unique ID of the template version."}},"required":["templateId","templateVersion"]},
    method: "put",
    pathTemplate: "/templates/{templateId}/versions/{templateVersion}/promote",
    executionParameters: [{"name":"templateId","in":"path"},{"name":"templateVersion","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["get_documents", {
    name: "get_documents",
    description: `Returns a list of generated documents created by authorized workspace and stored in PDF Generator API. If master user is specified as workspace in JWT then all documents created in the organization are returned. NB! This endpoint returns only documents generated using the output=url option.`,
    inputSchema: {"type":"object","properties":{"template_id":{"type":"number","description":"Template unique identifier"},"start_date":{"type":"string","description":"Start date. Format: Y-m-d H:i:s"},"end_date":{"type":"string","description":"End date. Format: Y-m-d H:i:s. Defaults to current timestamp"},"page":{"type":"number","default":1,"description":"Pagination: page to return"},"per_page":{"type":"number","default":15,"description":"Pagination: How many records to return per page"}}},
    method: "get",
    pathTemplate: "/documents",
    executionParameters: [{"name":"template_id","in":"query"},{"name":"start_date","in":"query"},{"name":"end_date","in":"query"},{"name":"page","in":"query"},{"name":"per_page","in":"query"}],
    requestBodyContentType: undefined,
  }],
  ["get_document", {
    name: "get_document",
    description: `Returns document stored in the Document Storage`,
    inputSchema: {"type":"object","properties":{"publicId":{"type":"string","description":"Resource public id"}},"required":["publicId"]},
    method: "get",
    pathTemplate: "/documents/{publicId}",
    executionParameters: [{"name":"publicId","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["delete_document", {
    name: "delete_document",
    description: `Delete document from the Document Storage`,
    inputSchema: {"type":"object","properties":{"publicId":{"type":"string","description":"Resource public id"}},"required":["publicId"]},
    method: "delete",
    pathTemplate: "/documents/{publicId}",
    executionParameters: [{"name":"publicId","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["generate_document", {
    name: "generate_document",
    description: `Merges template with data and returns base64 encoded document or a public URL to a document. NB! When the public URL option is used, the document is stored for 30 days and automatically deleted.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","properties":{"template":{"type":"object","description":"Template id, version, version id and data","properties":{"id":{"type":"number","description":"Template ID"},"version_id":{"type":"number","description":"Template version ID"},"data":{"oneOf":[{"type":"object","description":"JSON data used to replace data fields in the template","example":{"id":123,"name":"John Smith","birthdate":"2000-01-01","role":"Developer"}},{"type":"array","description":"JSON data used to replace data fields in the template","items":{"type":"object","description":"JSON data used to replace data fields in the template","example":{"id":123,"name":"John Smith","birthdate":"2000-01-01","role":"Developer"}},"example":[{"id":123,"name":"John Smith","birthdate":"2000-05-12","role":"Developer"},{"id":123,"name":"Jane Doe","birthdate":"1999-03-12","role":"Manager"}]}]}}},"format":{"description":"Document format. The zip option will return a ZIP file with PDF files.","type":"string","enum":["pdf","html","zip","xlsx"],"default":"pdf"},"output":{"description":"Response format. When the \"file\" option is used the API returns the file inline. With the \"url\" and \"viewer\" option, the document is stored for 30 days and automatically deleted.","type":"string","enum":["base64","url","file","viewer"],"default":"base64"},"name":{"type":"string","description":"Generated document name (optional)","default":""},"testing":{"type":"boolean","description":"When set to true the generation is not counted as merge (monthly usage), but a large PREVIEW stamp is added.","default":false},"metadata":{"type":"object","description":"Metadata object (optional)","properties":{"author":{"type":"string","description":"Document author","default":"Organization name"},"language":{"type":"string","description":"Document language","default":"en"}}}},"description":"Request parameters, including template id, data and formats."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/documents/generate",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["generate_document_async", {
    name: "generate_document_async",
    description: `Merges template with data as asynchronous job and makes POST request to callback URL defined in the request. Request uses the same format as response of synchronous generation endpoint.
The job id is also added to the callback request as header PDF-API-Job-Id

*Example response from callback URL:*
\`\`\`
{
  "response": "https://us1.pdfgeneratorapi.com/share/12821/VBERi0xLjcKJeLjz9MKNyAwIG9i",
  "meta": {
    "name": "a2bd25b8921f3dc7a440fd7f427f90a4.pdf",
    "display_name": "a2bd25b8921f3dc7a440fd7f427f90a4",
    "encoding": "binary",
    "content-type": "application/pdf"
  }
}
\`\`\`
`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","properties":{"template":{"type":"object","description":"Template id, version, version id and data","properties":{"id":{"type":"number","description":"Template ID"},"version_id":{"type":"number","description":"Template version ID"},"data":{"oneOf":[{"type":"object","description":"JSON data used to replace data fields in the template","example":{"id":123,"name":"John Smith","birthdate":"2000-01-01","role":"Developer"}},{"type":"array","description":"JSON data used to replace data fields in the template","items":{"type":"object","description":"JSON data used to replace data fields in the template","example":{"id":123,"name":"John Smith","birthdate":"2000-01-01","role":"Developer"}},"example":[{"id":123,"name":"John Smith","birthdate":"2000-05-12","role":"Developer"},{"id":123,"name":"Jane Doe","birthdate":"1999-03-12","role":"Manager"}]}]}}},"callback":{"type":"object","description":"Callback URL and optional headers","properties":{"url":{"type":"string","description":"Public callback URL that is used to make a POST request when the document is generated."},"headers":{"type":"object","description":"A key-value pairs of header values sent with the POST request."}}},"format":{"description":"Document format. The zip option will return a ZIP file with PDF files.","type":"string","enum":["pdf","html","zip","xlsx"],"default":"pdf"},"output":{"description":"The generated document is returned as base64 string or URL which is stored for 30 days and automatically deleted.","type":"string","enum":["base64","url","viewer"],"default":"base64"},"name":{"type":"string","description":"Generated document name (optional)","default":""},"testing":{"type":"boolean","description":"When set to true the generation is not counted as merge (monthly usage), but a large PREVIEW stamp is added.","default":false},"metadata":{"type":"object","description":"Metadata object (optional)","properties":{"author":{"type":"string","description":"Document author","default":"Organization name"},"language":{"type":"string","description":"Document language","default":"en"}}}},"description":"Request parameters, including template id, data and formats."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/documents/generate/async",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["generate_document_batch", {
    name: "generate_document_batch",
    description: `Allows to merge multiple templates with data and returns base64 encoded document or public URL to a document. NB! When the public URL option is used, the document is stored for 30 days and automatically deleted.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","properties":{"template":{"description":"Array of templates with data to generate documents from","type":"array","items":{"type":"object","description":"Template id, version, version id and data","properties":{"id":{"type":"number","description":"Template ID"},"version_id":{"type":"number","description":"Template version ID"},"data":{"oneOf":[{"type":"object","description":"JSON data used to replace data fields in the template","example":{"id":123,"name":"John Smith","birthdate":"2000-01-01","role":"Developer"}},{"type":"array","description":"JSON data used to replace data fields in the template","items":{"type":"object","description":"JSON data used to replace data fields in the template","example":{"id":123,"name":"John Smith","birthdate":"2000-01-01","role":"Developer"}},"example":[{"id":123,"name":"John Smith","birthdate":"2000-05-12","role":"Developer"},{"id":123,"name":"Jane Doe","birthdate":"1999-03-12","role":"Manager"}]}]}}}},"format":{"description":"Document format. The zip option will return a ZIP file with PDF files.","type":"string","enum":["pdf","html","zip","xlsx"],"default":"pdf"},"output":{"description":"Response format. When the \"file\" option is used the API returns the file inline. With the \"url\" and \"viewer\" option, the document is stored for 30 days and automatically deleted.","type":"string","enum":["base64","url","file","viewer"],"default":"base64"},"name":{"type":"string","description":"Generated document name (optional)","default":""},"testing":{"type":"boolean","description":"When set to true the generation is not counted as merge (monthly usage), but a large PREVIEW stamp is added.","default":false},"metadata":{"type":"object","description":"Metadata object (optional)","properties":{"author":{"type":"string","description":"Document author","default":"Organization name"},"language":{"type":"string","description":"Document language","default":"en"}}}},"description":"Request parameters, including template id, data and formats."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/documents/generate/batch",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["generate_document_batch_async", {
    name: "generate_document_batch_async",
    description: `Merges template with data as asynchronous job and makes POST request to callback URL defined in the request. Request uses the same format as response of synchronous generation endpoint.
The job id is also added to the callback request as header PDF-API-Job-Id

*Example response from callback URL:*
\`\`\`
{
  "response": "https://us1.pdfgeneratorapi.com/share/12821/VBERi0xLjcKJeLjz9MKNyAwIG9i",
  "meta": {
    "name": "a2bd25b8921f3dc7a440fd7f427f90a4.pdf",
    "display_name": "a2bd25b8921f3dc7a440fd7f427f90a4",
    "encoding": "binary",
    "content-type": "application/pdf"
  }
}
\`\`\`
`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","properties":{"template":{"description":"Array of templates with data to generate documents from","type":"array","items":{"type":"object","description":"Template id, version, version id and data","properties":{"id":{"type":"number","description":"Template ID"},"version_id":{"type":"number","description":"Template version ID"},"data":{"oneOf":[{"type":"object","description":"JSON data used to replace data fields in the template","example":{"id":123,"name":"John Smith","birthdate":"2000-01-01","role":"Developer"}},{"type":"array","description":"JSON data used to replace data fields in the template","items":{"type":"object","description":"JSON data used to replace data fields in the template","example":{"id":123,"name":"John Smith","birthdate":"2000-01-01","role":"Developer"}},"example":[{"id":123,"name":"John Smith","birthdate":"2000-05-12","role":"Developer"},{"id":123,"name":"Jane Doe","birthdate":"1999-03-12","role":"Manager"}]}]}}}},"callback":{"type":"object","description":"Callback URL and optional headers","properties":{"url":{"type":"string","description":"Public callback URL that is used to make a POST request when the document is generated."},"headers":{"type":"object","description":"A key-value pairs of header values sent with the POST request."}}},"format":{"description":"Document format. The zip option will return a ZIP file with PDF files.","type":"string","enum":["pdf","html","zip","xlsx"],"default":"pdf"},"output":{"description":"The generated document is returned as base64 string or URL which is stored for 30 days and automatically deleted.","type":"string","enum":["base64","url","viewer"],"default":"base64"},"name":{"type":"string","description":"Generated document name (optional)","default":""},"testing":{"type":"boolean","description":"When set to true the generation is not counted as merge (monthly usage), but a large PREVIEW stamp is added.","default":false},"metadata":{"type":"object","description":"Metadata object (optional)","properties":{"author":{"type":"string","description":"Document author","default":"Organization name"},"language":{"type":"string","description":"Document language","default":"en"}}}},"description":"Request parameters, including template id, data and formats."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/documents/generate/batch/async",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["get_async_job_status", {
    name: "get_async_job_status",
    description: `Returns status of an async job`,
    inputSchema: {"type":"object","properties":{"jobId":{"type":"string","description":"Job id"}},"required":["jobId"]},
    method: "get",
    pathTemplate: "/documents/async/{jobId}",
    executionParameters: [{"name":"jobId","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["get_workspaces", {
    name: "get_workspaces",
    description: `Returns all workspaces in the organization`,
    inputSchema: {"type":"object","properties":{"page":{"type":"number","default":1,"description":"Pagination: page to return"},"per_page":{"type":"number","default":15,"description":"Pagination: How many records to return per page"}}},
    method: "get",
    pathTemplate: "/workspaces",
    executionParameters: [{"name":"page","in":"query"},{"name":"per_page","in":"query"}],
    requestBodyContentType: undefined,
  }],
  ["create_workspace", {
    name: "create_workspace",
    description: `Creates a regular workspace with identifier specified in the request.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","properties":{"identifier":{"description":"A unique identifier of the workspace. Make sure that you can generate the same identifier for your user.","type":"string"}},"description":"The JSON request body."}}},
    method: "post",
    pathTemplate: "/workspaces",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["get_workspace", {
    name: "get_workspace",
    description: `Returns workspace information for the workspace identifier specified in the request.`,
    inputSchema: {"type":"object","properties":{"workspaceIdentifier":{"type":"string","description":"Workspace identifier"}},"required":["workspaceIdentifier"]},
    method: "get",
    pathTemplate: "/workspaces/{workspaceIdentifier}",
    executionParameters: [{"name":"workspaceIdentifier","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["delete_workspace", {
    name: "delete_workspace",
    description: `Delete workspace. Only regular workspaces can be deleted.`,
    inputSchema: {"type":"object","properties":{"workspaceIdentifier":{"type":"string","description":"Workspace identifier"}},"required":["workspaceIdentifier"]},
    method: "delete",
    pathTemplate: "/workspaces/{workspaceIdentifier}",
    executionParameters: [{"name":"workspaceIdentifier","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["convert_html_to_pdf", {
    name: "convert_html_to_pdf",
    description: `Converts HTML content to PDF`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","properties":{"content":{"type":"string","description":"HTML content"},"paper_size":{"type":"string","description":"PDF page size","enum":["a0","a1","a2","a3","a4","legal","tabloid","letter"],"default":"a4"},"orientation":{"type":"string","description":"Page orientation","enum":["portrait","landscape"],"default":"portrait"},"output":{"type":"string","description":"Output","enum":["base64","file"],"default":"base64"},"filename":{"type":"string","description":"Document name"}},"description":"The JSON request body."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/conversion/html2pdf",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["convert_url_to_pdf", {
    name: "convert_url_to_pdf",
    description: `Converts public URL to PDF`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","properties":{"url":{"type":"string","description":"Public URL"},"paper_size":{"type":"string","description":"PDF page size","enum":["a0","a1","a2","a3","a4","legal","tabloid","letter"],"default":"a4"},"orientation":{"type":"string","description":"Page orientation","enum":["portrait","landscape"],"default":"portrait"},"output":{"type":"string","description":"Output","enum":["base64","file"],"default":"base64"},"filename":{"type":"string","description":"Document name"}},"description":"The JSON request body."}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/conversion/url2pdf",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["get_forms", {
    name: "get_forms",
    description: `Returns a list of forms available for the organization`,
    inputSchema: {"type":"object","properties":{"page":{"type":"number","default":1,"description":"Pagination: page to return"},"per_page":{"type":"number","default":15,"description":"Pagination: How many records to return per page"}}},
    method: "get",
    pathTemplate: "/forms",
    executionParameters: [{"name":"page","in":"query"},{"name":"per_page","in":"query"}],
    requestBodyContentType: undefined,
  }],
  ["create_form", {
    name: "create_form",
    description: `Creates a new form based on the configuration sent in the request body.`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","properties":{"template_id":{"type":"number","description":"Template ID which is connected to the form"},"name":{"type":"string","description":"Form name"},"actions":{"type":"array","description":"Array of action configurations","items":{"anyOf":[{"type":"object","description":"Key-value pair of action configuration.","properties":{"store_document":{"type":"boolean","example":true}}},{"type":"object","description":"Key-value pair of action configuration.","properties":{"download_document":{"type":"boolean","example":true}}}]}},"fields":{"type":"array","description":"A list of form field objects","items":{"type":"object","description":"Form field definition","properties":{"label":{"type":"string","description":"Field label displayed in the form"},"name":{"type":"string","description":"Data field name. For example \"name\" can be used as \"{name}\" in the document as placeholder."},"type":{"type":"string","description":"Field type","enum":["text","integer","number","date","signature"]},"required":{"type":"boolean","description":"Specifies if the field is required or not"}}}}},"description":"Form configuration"}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/forms",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["import_form", {
    name: "import_form",
    description: `Creates a new form based on editable PDF`,
    inputSchema: {"type":"object","properties":{"requestBody":{"oneOf":[{"type":"object","required":["file_url"],"properties":{"file_url":{"description":"PDF file from remote URL to import","type":"string"},"form":{"description":"Form configuration with template, name, actions, and fields","type":"object","properties":{"template_id":{"type":"integer","description":"Template ID which is connected to the form","example":123123},"name":{"type":"string","description":"Form name","example":"Certificate creator"},"actions":{"type":"array","description":"Array of action configurations","items":{"anyOf":[{"type":"object","description":"Key-value pair of action configuration.","properties":{"store_document":{"type":"boolean","example":true}}},{"type":"object","description":"Key-value pair of action configuration.","properties":{"download_document":{"type":"boolean","example":true}}}]}},"fields":{"type":"array","description":"A list of form field objects","items":{"type":"object","description":"Form field definition","properties":{"label":{"type":"string","description":"Field label displayed in the form","example":"Full name"},"name":{"type":"string","description":"Data field name. For example \"name\" can be used as \"{name}\" in the document as placeholder.","example":"name"},"type":{"type":"string","description":"Field type","enum":["text","integer","number","date","signature"],"example":"text"},"required":{"type":"boolean","description":"Specifies if the field is required or not","example":false}}}}}}}},{"type":"object","required":["file_base64"],"properties":{"file_base64":{"description":"PDF file from base64 string to import","type":"string"},"form":{"description":"Form configuration with template, name, actions, and fields","type":"object","properties":{"template_id":{"type":"integer","description":"Template ID which is connected to the form","example":123123},"name":{"type":"string","description":"Form name","example":"Certificate creator"},"actions":{"type":"array","description":"Array of action configurations","items":{"anyOf":[{"type":"object","description":"Key-value pair of action configuration.","properties":{"store_document":{"type":"boolean","example":true}}},{"type":"object","description":"Key-value pair of action configuration.","properties":{"download_document":{"type":"boolean","example":true}}}]}},"fields":{"type":"array","description":"A list of form field objects","items":{"type":"object","description":"Form field definition","properties":{"label":{"type":"string","description":"Field label displayed in the form","example":"Full name"},"name":{"type":"string","description":"Data field name. For example \"name\" can be used as \"{name}\" in the document as placeholder.","example":"name"},"type":{"type":"string","description":"Field type","enum":["text","integer","number","date","signature"],"example":"text"},"required":{"type":"boolean","description":"Specifies if the field is required or not","example":false}}}}}}}}],"description":"Import editable PDF via URL or base64 string as form"}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/forms/import",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["get_form", {
    name: "get_form",
    description: `Returns form configuration`,
    inputSchema: {"type":"object","properties":{"formId":{"type":"number","description":"Form unique identifier"}},"required":["formId"]},
    method: "get",
    pathTemplate: "/forms/{formId}",
    executionParameters: [{"name":"formId","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["update_form", {
    name: "update_form",
    description: `Updates the form configuration. The form configuration must be complete as the entire configuration is replaced and not merged.`,
    inputSchema: {"type":"object","properties":{"formId":{"type":"number","description":"Form unique identifier"},"requestBody":{"type":"object","properties":{"template_id":{"type":"number","description":"Template ID which is connected to the form"},"name":{"type":"string","description":"Form name"},"actions":{"type":"array","description":"Array of action configurations","items":{"anyOf":[{"type":"object","description":"Key-value pair of action configuration.","properties":{"store_document":{"type":"boolean","example":true}}},{"type":"object","description":"Key-value pair of action configuration.","properties":{"download_document":{"type":"boolean","example":true}}}]}},"fields":{"type":"array","description":"A list of form field objects","items":{"type":"object","description":"Form field definition","properties":{"label":{"type":"string","description":"Field label displayed in the form"},"name":{"type":"string","description":"Data field name. For example \"name\" can be used as \"{name}\" in the document as placeholder."},"type":{"type":"string","description":"Field type","enum":["text","integer","number","date","signature"]},"required":{"type":"boolean","description":"Specifies if the field is required or not"}}}}},"description":"Form configuration"}},"required":["formId","requestBody"]},
    method: "put",
    pathTemplate: "/forms/{formId}",
    executionParameters: [{"name":"formId","in":"path"}],
    requestBodyContentType: "application/json",
  }],
  ["delete_form", {
    name: "delete_form",
    description: `Deletes the form with specified id`,
    inputSchema: {"type":"object","properties":{"formId":{"type":"number","description":"Form unique identifier"}},"required":["formId"]},
    method: "delete",
    pathTemplate: "/forms/{formId}",
    executionParameters: [{"name":"formId","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["share_form", {
    name: "share_form",
    description: `Creates an unique sharing URL to collect form data`,
    inputSchema: {"type":"object","properties":{"formId":{"type":"number","description":"Form unique identifier"}},"required":["formId"]},
    method: "post",
    pathTemplate: "/forms/{formId}/share",
    executionParameters: [{"name":"formId","in":"path"}],
    requestBodyContentType: undefined,
  }],
  ["generate_qr_code", {
    name: "generate_qr_code",
    description: `Creates a QR code based on the configuration`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","required":["content"],"properties":{"content":{"type":"string","description":"The content which is used to generate QR code"},"color":{"description":"QR code in hexadecimal format","type":"string","default":"#000000"},"logo_base64":{"description":"A logo as a base64 image string to add on the QR code","type":"string"},"logo_url":{"description":"A logo URL to an image to add on the QR code","type":"string"},"output":{"description":"Response format","type":"string","enum":["file","base64"],"default":"base64"}},"description":"QR Code configuration"}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/assets/qrcode",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["create_einvoice", {
    name: "create_einvoice",
    description: `This endpoint transforms a JSON payload into an XML-based e-invoice that is fully compliant with the European EN 16931 standard. The generated output can be formatted in either UBL (Universal Business Language) or CII (Cross-Industry Invoice) syntax, ensuring interoperability across B2B and B2G platforms. The JSON payload follows Peppol BIS Billing 3.0 UBL Invoice described here: https://docs.peppol.eu/poacc/billing/3.0/`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","required":["data"],"properties":{"data":{"description":"JSON payload that represents the Peppol BIS Billing 3.0 UBL Invoice (https://docs.peppol.eu/poacc/billing/3.0/) Use the Get schema endpoint to see the detailed payload structure.","type":"object"},"type":{"description":"Formatting type.","type":"string","enum":["UBL","CII"],"default":"UBL"},"output":{"description":"Response format. When the \"file\" option is used the API returns the file inline.","type":"string","enum":["base64","file"],"default":"base64"}},"description":"eInvoice conversion"}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/einvoice",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["create_xrechnung_einvoice", {
    name: "create_xrechnung_einvoice",
    description: `This endpoint transforms a JSON payload into an XML-based XRechnung e-invoice that is fully compliant with the European EN 16931 standard. The generated output follows the XRechnung format and can be formatted in either UBL (Universal Business Language) or CII (Cross-Industry Invoice) syntax, ensuring interoperability across B2B and B2G platforms. The JSON payload follows Peppol BIS Billing 3.0 UBL Invoice described here: https://docs.peppol.eu/poacc/billing/3.0/`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","required":["data"],"properties":{"data":{"description":"JSON payload that represents the Peppol BIS Billing 3.0 UBL Invoice (https://docs.peppol.eu/poacc/billing/3.0/) Use the Get schema endpoint to see the detailed payload structure.","type":"object"},"type":{"description":"Formatting type.","type":"string","enum":["UBL","CII"],"default":"UBL"},"output":{"description":"Response format. When the \"file\" option is used the API returns the file inline.","type":"string","enum":["base64","file"],"default":"base64"}},"description":"eInvoice conversion"}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/einvoice/xrechnung",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["create_facturx_einvoice", {
    name: "create_facturx_einvoice",
    description: `This endpoint transforms a JSON payload a Factur-X e-invoice that is fully compliant with the European EN 16931 standard. The generated output is always a PDF document, embedding a structured CII (Cross-Industry Invoice) XML according to the Factur-X format into a human-readable invoice, ensuring interoperability across B2B and B2G platforms. The JSON payload follows Peppol BIS Billing 3.0 UBL Invoice described here: https://docs.peppol.eu/poacc/billing/3.0/`,
    inputSchema: {"type":"object","properties":{"requestBody":{"type":"object","required":["template"],"properties":{"template":{"type":"object","description":"Template id, version, version id and data","properties":{"id":{"type":"number","description":"Template ID"},"version_id":{"type":"number","description":"Template version ID"},"data":{"description":"JSON payload that represents the Peppol BIS Billing 3.0 UBL Invoice (https://docs.peppol.eu/poacc/billing/3.0/) Use the Get schema endpoint to see the detailed payload structure.","type":"object"}}},"profile":{"description":"Factur-X conformance level.","type":"string","enum":["basic","basicwl","en16931","minimum","extended","xrechnung"],"default":"basic"},"output":{"description":"Response format. When the \"file\" option is used the API returns the file inline. With the \"url\" and \"viewer\" option, the document is stored for 30 days and automatically deleted.","type":"string","enum":["base64","url","file","viewer"],"default":"base64"},"name":{"type":"string","description":"Generated document name (optional)","default":""},"metadata":{"type":"object","description":"Metadata object (optional)","properties":{"author":{"type":"string","description":"Document author","default":"Organization name"},"language":{"type":"string","description":"Document language","default":"en"}}}},"description":"eInvoice conversion"}},"required":["requestBody"]},
    method: "post",
    pathTemplate: "/einvoice/facturx",
    executionParameters: [],
    requestBodyContentType: "application/json",
  }],
  ["get_einvoice_schema", {
    name: "get_einvoice_schema",
    description: `Returns e-invoice JSON schema which defines the structure of the e-invoice.`,
    inputSchema: {"type":"object","properties":{}},
    method: "get",
    pathTemplate: "/einvoice/schema",
    executionParameters: [],
    requestBodyContentType: undefined,
  }],
]);
